/* TubeScrapeBoogie — Sidebar Content Script (IIFE) */
/* No ES module imports — content scripts cannot use them */
(function () {
  'use strict';

  // ─── Guard: only inject once ──────────────────────────────────
  if (document.getElementById('tsb-sidebar')) return;

  // ─── State ────────────────────────────────────────────────────
  const state = {
    isOpen: false,
    segments: [],          // full transcript [{start, duration, text}]
    filteredIndices: [],   // indices into segments that pass search
    keywords: [],          // [{term, color}]
    meta: null,            // {id, title, channel, viewCount, publishDate}
    captionTracks: [],     // [{url, label, languageCode, isAutoGenerated}]
    selectedTrackUrl: null,
    searchQuery: '',
    autoScroll: true,
    activeLineIndex: -1,
    playbackTimer: null,
    isResizing: false,
    resizeStartX: 0,
    resizeStartWidth: 0,
  };

  // ─── Helpers ──────────────────────────────────────────────────
  function formatTimestamp(seconds) {
    const t = Math.floor(seconds);
    const h = Math.floor(t / 3600);
    const m = Math.floor((t % 3600) / 60);
    const s = t % 60;
    if (h > 0) {
      return `${h}:${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}`;
    }
    return `${m}:${String(s).padStart(2, '0')}`;
  }

  function formatViewCount(n) {
    if (!n) return '';
    if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + 'M views';
    if (n >= 1_000)     return (n / 1_000).toFixed(0) + 'K views';
    return n.toLocaleString() + ' views';
  }

  function escapeHtml(str) {
    return str
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  function escapeRegex(str) {
    return str.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  }

  function getVideoPlayer() {
    return (
      document.querySelector('video.html5-main-video') ||
      document.querySelector('video')
    );
  }

  function getCurrentVideoTime() {
    const v = getVideoPlayer();
    return v ? v.currentTime : 0;
  }

  // ─── Build DOM ────────────────────────────────────────────────
  function buildSidebar() {
    const sidebar = document.createElement('div');
    sidebar.id = 'tsb-sidebar';
    sidebar.setAttribute('role', 'complementary');
    sidebar.setAttribute('aria-label', 'TubeScrapeBoogie transcript panel');

    sidebar.innerHTML = `
      <!-- Resize handle -->
      <div id="tsb-resize-handle" aria-hidden="true"></div>

      <!-- Header -->
      <div id="tsb-header">
        <span id="tsb-header-title">Tube<span>Scrape</span>Boogie</span>
        <button class="tsb-header-btn" id="tsb-autoscroll-btn" title="Toggle auto-scroll" aria-pressed="true">
          <span class="tsb-dot"></span>
          <span>AUTO</span>
        </button>
        <button class="tsb-header-btn" id="tsb-settings-btn" title="Settings / Library" aria-label="Open library dashboard">
          <svg viewBox="0 0 24 24">
            <circle cx="12" cy="12" r="3"/>
            <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/>
          </svg>
        </button>
        <button class="tsb-header-btn" id="tsb-close-btn" title="Close sidebar" aria-label="Close sidebar">
          <svg viewBox="0 0 24 24">
            <path d="M18 6L6 18M6 6l12 12"/>
          </svg>
        </button>
      </div>

      <!-- Video Info Strip -->
      <div id="tsb-video-info">
        <div id="tsb-video-title">Loading video info…</div>
        <div id="tsb-video-meta">
          <span class="tsb-channel">—</span>
        </div>
      </div>

      <!-- Controls -->
      <div id="tsb-controls">
        <div id="tsb-lang-row">
          <span id="tsb-lang-label">Track</span>
          <select id="tsb-lang-select" aria-label="Caption track">
            <option value="">— no captions —</option>
          </select>
        </div>
        <div id="tsb-search-wrap">
          <svg id="tsb-search-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <circle cx="11" cy="11" r="8"/><path d="m21 21-4.35-4.35"/>
          </svg>
          <input
            id="tsb-search-input"
            type="search"
            placeholder="Search transcript…"
            autocomplete="off"
            spellcheck="false"
            aria-label="Search transcript"
          />
        </div>
        <div id="tsb-keyword-badge" role="status" aria-live="polite">
          <span class="tsb-badge-dot"></span>
          <span id="tsb-keyword-badge-text">0 keyword matches</span>
        </div>
      </div>

      <!-- Search results count -->
      <div id="tsb-search-count" aria-live="polite"></div>

      <!-- Transcript -->
      <div id="tsb-transcript" role="log" aria-label="Video transcript" aria-live="off">
        <div id="tsb-transcript-state">
          <div class="tsb-spinner"></div>
          Loading transcript…
        </div>
        <ul id="tsb-lines" hidden></ul>
      </div>

      <!-- Action Bar -->
      <div id="tsb-actions">
        <button class="tsb-action-btn" id="tsb-copy-btn" title="Copy full transcript">
          <svg viewBox="0 0 24 24"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
          Copy
        </button>
        <button class="tsb-action-btn" id="tsb-save-btn" title="Save to library">
          <svg viewBox="0 0 24 24"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/></svg>
          Save
        </button>
        <div id="tsb-export-wrap">
          <button class="tsb-action-btn" id="tsb-export-btn" title="Export transcript" aria-haspopup="true" aria-expanded="false">
            <svg viewBox="0 0 24 24"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>
            Export
            <svg viewBox="0 0 24 24" style="width:8px;height:8px;margin-left:1px"><polyline points="6 9 12 15 18 9"/></svg>
          </button>
          <div id="tsb-export-menu" role="menu" aria-label="Export formats">
            <button class="tsb-export-item" data-format="text" role="menuitem">
              Plain Text <span class="tsb-export-item-ext">.txt</span>
            </button>
            <button class="tsb-export-item" data-format="markdown" role="menuitem">
              Markdown <span class="tsb-export-item-ext">.md</span>
            </button>
            <button class="tsb-export-item" data-format="csv" role="menuitem">
              CSV <span class="tsb-export-item-ext">.csv</span>
            </button>
            <button class="tsb-export-item" data-format="json" role="menuitem">
              JSON <span class="tsb-export-item-ext">.json</span>
            </button>
            <button class="tsb-export-item" data-format="srt" role="menuitem">
              SubRip <span class="tsb-export-item-ext">.srt</span>
            </button>
            <button class="tsb-export-item" data-format="ai" role="menuitem">
              AI Prompt <span class="tsb-export-item-ext">.txt</span>
            </button>
          </div>
        </div>
        <button class="tsb-action-btn" id="tsb-library-btn" title="Open library" style="margin-left:auto">
          <svg viewBox="0 0 24 24"><path d="M4 19.5A2.5 2.5 0 0 1 6.5 17H20"/><path d="M6.5 2H20v20H6.5A2.5 2.5 0 0 1 4 19.5v-15A2.5 2.5 0 0 1 6.5 2z"/></svg>
          Library
        </button>
      </div>

      <!-- Toast -->
      <div id="tsb-toast" role="alert" aria-live="assertive"></div>
    `;

    document.body.appendChild(sidebar);
    return sidebar;
  }

  // ─── DOM References (populated after buildSidebar) ───────────
  let els = {};

  function cacheElements() {
    const ids = [
      'tsb-sidebar', 'tsb-resize-handle', 'tsb-header-title',
      'tsb-autoscroll-btn', 'tsb-settings-btn', 'tsb-close-btn',
      'tsb-video-title', 'tsb-video-meta',
      'tsb-lang-select', 'tsb-search-input', 'tsb-search-count',
      'tsb-keyword-badge', 'tsb-keyword-badge-text',
      'tsb-transcript', 'tsb-transcript-state', 'tsb-lines',
      'tsb-copy-btn', 'tsb-save-btn', 'tsb-export-btn', 'tsb-export-menu',
      'tsb-library-btn', 'tsb-toast',
    ];
    ids.forEach(id => {
      const key = id.replace('tsb-', '').replace(/-([a-z])/g, (_, c) => c.toUpperCase());
      els[key] = document.getElementById(id);
    });
  }

  // ─── Toast ────────────────────────────────────────────────────
  let toastTimer = null;
  function showToast(msg, type = 'info', duration = 2200) {
    const t = els.toast;
    if (!t) return;
    t.textContent = msg;
    t.className = `tsb-toast-show tsb-toast-${type}`;
    if (toastTimer) clearTimeout(toastTimer);
    toastTimer = setTimeout(() => {
      t.className = '';
    }, duration);
  }

  // ─── Open / Close ─────────────────────────────────────────────
  function openSidebar() {
    if (state.isOpen) return;
    state.isOpen = true;
    els.sidebar.classList.add('tsb-open');
    document.documentElement.classList.add('tsb-sidebar-open');
    loadVideoData();
    startPlaybackTracking();
  }

  function closeSidebar() {
    if (!state.isOpen) return;
    state.isOpen = false;
    els.sidebar.classList.remove('tsb-open');
    document.documentElement.classList.remove('tsb-sidebar-open');
    stopPlaybackTracking();
  }

  function toggleSidebar() {
    if (state.isOpen) {
      closeSidebar();
    } else {
      openSidebar();
    }
  }

  // ─── Extract Data Directly From Page ───────────────────────────
  function getPlayerResponseFromPage() {
    // YouTube updates window.ytInitialPlayerResponse on every SPA navigation
    if (window.ytInitialPlayerResponse && window.ytInitialPlayerResponse.videoDetails) {
      return window.ytInitialPlayerResponse;
    }
    // Fallback: parse from script tags (first load only)
    const scripts = document.querySelectorAll('script');
    for (const script of scripts) {
      const text = script.textContent;
      const match = text.match(/var\s+ytInitialPlayerResponse\s*=\s*(\{.+?\});/s);
      if (match) {
        try { return JSON.parse(match[1]); } catch { continue; }
      }
    }
    return null;
  }

  function extractCaptionTracks(pr) {
    const tracks = pr?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    if (!tracks) return [];
    return tracks.map(t => ({
      url: t.baseUrl,
      label: t.name?.simpleText || t.languageCode,
      languageCode: t.languageCode,
      isAutoGenerated: t.kind === 'asr',
    }));
  }

  function extractMetadata(pr) {
    const d = pr?.videoDetails;
    if (!d) return null;
    return {
      id: d.videoId,
      title: d.title,
      channel: d.author,
      channelId: d.channelId,
      description: d.shortDescription || '',
      viewCount: parseInt(d.viewCount, 10) || 0,
      publishDate: d.publishDate || '',
    };
  }

  // ─── Load Video Data ──────────────────────────────────────────
  function loadVideoData() {
    setTranscriptState('loading', 'Loading transcript…');

    const playerResponse = getPlayerResponseFromPage();
    if (!playerResponse) {
      setTranscriptState('error', 'Could not read video data. Try refreshing the page.');
      return;
    }

    state.meta = extractMetadata(playerResponse);
    state.captionTracks = extractCaptionTracks(playerResponse);

    updateVideoInfoStrip();
    populateLangSelector();
    loadKeywords();

    if (state.captionTracks.length > 0) {
      const preferred = state.captionTracks.find(t => !t.isAutoGenerated) || state.captionTracks[0];
      state.selectedTrackUrl = preferred.url;
      els.langSelect.value = preferred.url;
      fetchTranscript(preferred.url);
    } else {
      setTranscriptState('empty', 'No captions available for this video.');
    }
  }

  function updateVideoInfoStrip() {
    const m = state.meta;
    if (!m) return;
    els.videoTitle.textContent = m.title || 'Untitled Video';
    const parts = [];
    if (m.channel) parts.push(`<span class="tsb-channel">${escapeHtml(m.channel)}</span>`);
    if (m.viewCount) parts.push(`<span>${escapeHtml(formatViewCount(m.viewCount))}</span>`);
    if (m.publishDate) parts.push(`<span>${escapeHtml(m.publishDate)}</span>`);
    els.videoMeta.innerHTML = parts.join('<span class="tsb-meta-sep"> · </span>');
  }

  function populateLangSelector() {
    const sel = els.langSelect;
    sel.innerHTML = '';
    if (state.captionTracks.length === 0) {
      sel.innerHTML = '<option value="">— no captions —</option>';
      return;
    }
    state.captionTracks.forEach(track => {
      const opt = document.createElement('option');
      opt.value = track.url;
      opt.textContent = track.label + (track.isAutoGenerated ? ' (auto)' : '');
      sel.appendChild(opt);
    });
  }

  // ─── Fetch Transcript ─────────────────────────────────────────
  function fetchTranscript(captionUrl) {
    if (!captionUrl) {
      setTranscriptState('empty', 'Select a caption track above.');
      return;
    }
    setTranscriptState('loading', 'Fetching transcript…');

    chrome.runtime.sendMessage({ type: 'FETCH_TRANSCRIPT', captionUrl }, (response) => {
      if (chrome.runtime.lastError || !response || response.error) {
        const errMsg = (response && response.error) ? response.error : 'Failed to load transcript.';
        setTranscriptState('error', errMsg);
        return;
      }

      state.segments = response.segments || [];
      state.filteredIndices = state.segments.map((_, i) => i);

      if (state.segments.length === 0) {
        setTranscriptState('empty', 'Transcript is empty.');
        return;
      }

      renderTranscript();
      updateKeywordBadge();
    });
  }

  // ─── State Display ────────────────────────────────────────────
  function setTranscriptState(type, message) {
    els.transcriptState.hidden = false;
    els.lines.hidden = true;

    if (type === 'loading') {
      els.transcriptState.innerHTML = `<div class="tsb-spinner"></div>${escapeHtml(message)}`;
    } else if (type === 'error') {
      els.transcriptState.innerHTML = `<span class="tsb-state-icon">⚠</span>${escapeHtml(message)}`;
    } else {
      els.transcriptState.innerHTML = `<span class="tsb-state-icon">◌</span>${escapeHtml(message)}`;
    }
  }

  // ─── Render Transcript ────────────────────────────────────────
  function renderTranscript() {
    const list = els.lines;
    list.innerHTML = '';

    const query = state.searchQuery.trim().toLowerCase();

    state.segments.forEach((seg, i) => {
      const li = document.createElement('li');
      li.className = 'tsb-line';
      li.dataset.index = i;
      li.dataset.start = seg.start;

      // Stagger animation
      li.style.animationDelay = `${Math.min(i * 12, 400)}ms`;

      // Timestamp
      const tsEl = document.createElement('span');
      tsEl.className = 'tsb-line-ts';
      tsEl.textContent = formatTimestamp(seg.start);

      // Line number
      const numEl = document.createElement('span');
      numEl.className = 'tsb-line-num';
      numEl.textContent = i + 1;
      numEl.setAttribute('aria-hidden', 'true');

      // Text with highlights
      const textEl = document.createElement('span');
      textEl.className = 'tsb-line-text';
      textEl.innerHTML = buildHighlightedText(seg.text, query, state.keywords);

      li.appendChild(numEl);
      li.appendChild(tsEl);
      li.appendChild(textEl);

      // Click to seek
      li.addEventListener('click', () => {
        const video = getVideoPlayer();
        if (video) {
          video.currentTime = seg.start;
          video.play().catch(() => {});
        }
        setActiveLine(i);
      });

      // Visibility based on search filter
      if (query && !seg.text.toLowerCase().includes(query)) {
        li.classList.add('tsb-line-hidden');
      }

      list.appendChild(li);
    });

    els.transcriptState.hidden = true;
    list.hidden = false;

    updateSearchCount();
    updateKeywordBadge();
  }

  // ─── Highlight Text ───────────────────────────────────────────
  function buildHighlightedText(rawText, searchQuery, keywords) {
    let text = escapeHtml(rawText);

    // Build a list of all ranges to highlight
    const ranges = [];

    // Keyword ranges
    keywords.forEach(kw => {
      if (!kw.term) return;
      const regex = new RegExp(escapeRegex(escapeHtml(kw.term)), 'gi');
      let m;
      while ((m = regex.exec(text)) !== null) {
        ranges.push({ start: m.index, end: m.index + m[0].length, type: 'keyword' });
      }
    });

    // Search ranges
    if (searchQuery) {
      const regex = new RegExp(escapeRegex(escapeHtml(searchQuery)), 'gi');
      let m;
      while ((m = regex.exec(text)) !== null) {
        ranges.push({ start: m.index, end: m.index + m[0].length, type: 'search' });
      }
    }

    if (ranges.length === 0) return text;

    // Sort and apply non-overlapping ranges (search beats keyword)
    ranges.sort((a, b) => a.start - b.start);
    const merged = [];
    ranges.forEach(r => {
      if (merged.length === 0 || r.start >= merged[merged.length - 1].end) {
        merged.push({ ...r });
      } else if (r.type === 'search') {
        // Search highlight overrides keyword in overlaps
        merged[merged.length - 1] = r;
      }
    });

    let result = '';
    let cursor = 0;
    merged.forEach(r => {
      result += text.slice(cursor, r.start);
      const cls = r.type === 'search' ? 'tsb-highlight-search' : 'tsb-highlight-keyword';
      result += `<mark class="${cls}">${text.slice(r.start, r.end)}</mark>`;
      cursor = r.end;
    });
    result += text.slice(cursor);
    return result;
  }

  // ─── Active Line ──────────────────────────────────────────────
  function setActiveLine(index) {
    // Remove previous
    const prev = els.lines.querySelector('.tsb-line-active');
    if (prev) prev.classList.remove('tsb-line-active');

    state.activeLineIndex = index;
    if (index < 0) return;

    const li = els.lines.querySelector(`[data-index="${index}"]`);
    if (li) {
      li.classList.add('tsb-line-active');
      if (state.autoScroll) {
        li.scrollIntoView({ block: 'nearest', behavior: 'smooth' });
      }
    }
  }

  function findActiveLineIndex(currentTime) {
    const segs = state.segments;
    if (!segs.length) return -1;
    let idx = 0;
    for (let i = 0; i < segs.length; i++) {
      if (segs[i].start <= currentTime) {
        idx = i;
      } else {
        break;
      }
    }
    return idx;
  }

  // ─── Playback Tracking ────────────────────────────────────────
  function startPlaybackTracking() {
    stopPlaybackTracking();
    state.playbackTimer = setInterval(() => {
      if (!state.isOpen || state.segments.length === 0) return;
      const t = getCurrentVideoTime();
      const idx = findActiveLineIndex(t);
      if (idx !== state.activeLineIndex) {
        setActiveLine(idx);
      }
    }, 500);
  }

  function stopPlaybackTracking() {
    if (state.playbackTimer) {
      clearInterval(state.playbackTimer);
      state.playbackTimer = null;
    }
  }

  // ─── Keywords ─────────────────────────────────────────────────
  function loadKeywords() {
    chrome.storage.local.get('tsb_keywords', (result) => {
      state.keywords = result.tsb_keywords || [];
      if (state.segments.length > 0) {
        renderTranscript();
      }
    });
  }

  function countKeywordMatches() {
    if (!state.keywords.length || !state.segments.length) return 0;
    const fullText = state.segments.map(s => s.text).join(' ').toLowerCase();
    let total = 0;
    state.keywords.forEach(kw => {
      if (!kw.term) return;
      const regex = new RegExp(escapeRegex(kw.term.toLowerCase()), 'g');
      const found = fullText.match(regex);
      if (found) total += found.length;
    });
    return total;
  }

  function updateKeywordBadge() {
    const count = countKeywordMatches();
    if (count > 0) {
      els.keywordBadge.classList.add('tsb-visible');
      const noun = count === 1 ? 'match' : 'matches';
      els.keywordBadgeText.textContent = `${count} keyword ${noun} found`;
    } else {
      els.keywordBadge.classList.remove('tsb-visible');
    }
  }

  // ─── Search ───────────────────────────────────────────────────
  function applySearch(query) {
    state.searchQuery = query;
    const q = query.trim().toLowerCase();

    const items = els.lines.querySelectorAll('.tsb-line');
    let visibleCount = 0;

    items.forEach((li, i) => {
      const seg = state.segments[i];
      if (!seg) return;

      // Update highlight
      const textEl = li.querySelector('.tsb-line-text');
      if (textEl) {
        textEl.innerHTML = buildHighlightedText(seg.text, q, state.keywords);
      }

      const matches = !q || seg.text.toLowerCase().includes(q);
      if (matches) {
        li.classList.remove('tsb-line-hidden');
        visibleCount++;
      } else {
        li.classList.add('tsb-line-hidden');
      }
    });

    updateSearchCount(q, visibleCount, items.length);
  }

  function updateSearchCount(query, visible, total) {
    const el = els.searchCount;
    if (!el) return;
    if (query && query.trim()) {
      el.textContent = `${visible} of ${total} lines`;
      el.classList.add('tsb-visible');
    } else {
      el.classList.remove('tsb-visible');
    }
  }

  // ─── Copy Transcript ──────────────────────────────────────────
  function copyTranscript() {
    if (!state.segments.length) {
      showToast('No transcript to copy.', 'error');
      return;
    }
    const lines = state.segments.map(s => `${formatTimestamp(s.start)}  ${s.text}`);
    const text = (state.meta ? `${state.meta.title}\n\n` : '') + lines.join('\n');
    navigator.clipboard.writeText(text).then(() => {
      showToast('Copied to clipboard.', 'success');
    }).catch(() => {
      showToast('Copy failed.', 'error');
    });
  }

  // ─── Save Transcript ──────────────────────────────────────────
  function saveTranscript() {
    if (!state.segments.length || !state.meta) {
      showToast('Nothing to save.', 'error');
      return;
    }
    chrome.storage.local.get('tsb_transcripts', (result) => {
      const map = result.tsb_transcripts || {};
      map[state.meta.id] = {
        id: state.meta.id,
        savedAt: new Date().toISOString(),
        metadata: state.meta,
        segments: state.segments,
      };
      chrome.storage.local.set({ tsb_transcripts: map }, () => {
        if (chrome.runtime.lastError) {
          showToast('Save failed.', 'error');
        } else {
          showToast('Saved to library.', 'success');
        }
      });
    });
  }

  // ─── Export ───────────────────────────────────────────────────
  function exportTranscript(format) {
    if (!state.segments.length) {
      showToast('No transcript to export.', 'error');
      return;
    }
    const meta = state.meta || { title: 'transcript', channel: '', viewCount: 0, publishDate: '' };
    let content = '';
    let filename = '';
    let mimeType = 'text/plain';

    switch (format) {
      case 'text': {
        const header = `${meta.title}\nChannel: ${meta.channel}\nPublished: ${meta.publishDate}\n\n`;
        content = header + state.segments.map(s => `${formatTimestamp(s.start)} ${s.text}`).join('\n');
        filename = `transcript-${meta.id || 'video'}.txt`;
        break;
      }
      case 'markdown': {
        const lines = [
          `# ${meta.title}`, '',
          `- **Channel:** ${meta.channel}`,
          `- **Published:** ${meta.publishDate}`,
          `- **Views:** ${(meta.viewCount || 0).toLocaleString()}`,
          '', '---', '',
          ...state.segments.map(s => `**${formatTimestamp(s.start)}** ${s.text}`),
        ];
        content = lines.join('\n');
        filename = `transcript-${meta.id || 'video'}.md`;
        mimeType = 'text/markdown';
        break;
      }
      case 'csv': {
        const rows = ['timestamp,start_seconds,text'];
        state.segments.forEach(s => {
          rows.push(`"${formatTimestamp(s.start)}",${s.start},"${s.text.replace(/"/g, '""')}"`);
        });
        content = rows.join('\n');
        filename = `transcript-${meta.id || 'video'}.csv`;
        mimeType = 'text/csv';
        break;
      }
      case 'json': {
        content = JSON.stringify({ metadata: meta, segments: state.segments }, null, 2);
        filename = `transcript-${meta.id || 'video'}.json`;
        mimeType = 'application/json';
        break;
      }
      case 'srt': {
        const srtTs = (sec) => {
          const h  = Math.floor(sec / 3600);
          const m  = Math.floor((sec % 3600) / 60);
          const s  = Math.floor(sec % 60);
          const ms = Math.round((sec % 1) * 1000);
          return `${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')},${String(ms).padStart(3,'0')}`;
        };
        content = state.segments.map((s, i) => {
          const end = s.start + (s.duration || 1);
          return `${i + 1}\n${srtTs(s.start)} --> ${srtTs(end)}\n${s.text}`;
        }).join('\n\n');
        filename = `transcript-${meta.id || 'video'}.srt`;
        break;
      }
      case 'ai': {
        const transcript = state.segments.map(s => s.text).join(' ');
        content = [
          'The following is a transcript from a YouTube video:',
          '',
          `Title: ${meta.title}`,
          `Channel: ${meta.channel}`,
          `Published: ${meta.publishDate}`,
          `Views: ${(meta.viewCount || 0).toLocaleString()}`,
          '',
          '--- BEGIN TRANSCRIPT ---',
          '',
          transcript,
          '',
          '--- END TRANSCRIPT ---',
        ].join('\n');
        filename = `transcript-ai-${meta.id || 'video'}.txt`;
        break;
      }
      default:
        showToast('Unknown format.', 'error');
        return;
    }

    // Trigger download
    const blob = new Blob([content], { type: mimeType + ';charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    a.remove();
    setTimeout(() => URL.revokeObjectURL(url), 1000);
    showToast(`Exported as ${format.toUpperCase()}.`, 'success');
  }

  // ─── Export Dropdown ──────────────────────────────────────────
  function toggleExportMenu() {
    const isOpen = els.exportMenu.classList.toggle('tsb-open');
    els.exportBtn.setAttribute('aria-expanded', isOpen ? 'true' : 'false');
  }

  function closeExportMenu() {
    els.exportMenu.classList.remove('tsb-open');
    els.exportBtn.setAttribute('aria-expanded', 'false');
  }

  // ─── Resize Handle ────────────────────────────────────────────
  function initResizeHandle() {
    const handle = document.getElementById('tsb-resize-handle');

    handle.addEventListener('mousedown', (e) => {
      e.preventDefault();
      state.isResizing = true;
      state.resizeStartX = e.clientX;
      state.resizeStartWidth = els.sidebar.getBoundingClientRect().width;
      handle.classList.add('tsb-resizing');
      document.body.style.userSelect = 'none';
      document.body.style.cursor = 'col-resize';
    });

    document.addEventListener('mousemove', (e) => {
      if (!state.isResizing) return;
      const delta = state.resizeStartX - e.clientX;
      const newWidth = Math.min(800, Math.max(300, state.resizeStartWidth + delta));
      els.sidebar.style.width = newWidth + 'px';
      document.documentElement.style.setProperty('--tsb-sidebar-width', newWidth + 'px');
    });

    document.addEventListener('mouseup', () => {
      if (!state.isResizing) return;
      state.isResizing = false;
      handle.classList.remove('tsb-resizing');
      document.body.style.userSelect = '';
      document.body.style.cursor = '';

      // Persist sidebar width
      const width = els.sidebar.getBoundingClientRect().width;
      chrome.storage.local.get('tsb_settings', (r) => {
        const settings = r.tsb_settings || {};
        settings.sidebarWidth = width;
        chrome.storage.local.set({ tsb_settings: settings });
      });
    });
  }

  // ─── Auto-scroll Toggle ───────────────────────────────────────
  function updateAutoScrollBtn() {
    const btn = els.autoscrollBtn;
    if (state.autoScroll) {
      btn.classList.add('tsb-active');
      btn.title = 'Auto-scroll: ON';
      btn.setAttribute('aria-pressed', 'true');
    } else {
      btn.classList.remove('tsb-active');
      btn.title = 'Auto-scroll: OFF';
      btn.setAttribute('aria-pressed', 'false');
    }
  }

  // ─── SPA Navigation ───────────────────────────────────────────
  function handleVideoChanged() {
    // Reset state for new video
    state.segments = [];
    state.filteredIndices = [];
    state.meta = null;
    state.captionTracks = [];
    state.selectedTrackUrl = null;
    state.activeLineIndex = -1;
    state.searchQuery = '';

    if (els.searchInput) els.searchInput.value = '';
    if (els.keywordBadge) els.keywordBadge.classList.remove('tsb-visible');

    setTranscriptState('loading', 'Loading new video…');
    els.videoTitle.textContent = 'Loading…';
    els.videoMeta.innerHTML = '';

    if (state.isOpen) {
      setTimeout(loadVideoData, 800); // slight delay for YouTube SPA to settle
    }
  }

  // ─── Load Saved Width ─────────────────────────────────────────
  function loadSavedWidth() {
    chrome.storage.local.get('tsb_settings', (r) => {
      const settings = r.tsb_settings || {};
      const width = settings.sidebarWidth;
      const autoScroll = settings.autoScroll !== undefined ? settings.autoScroll : true;
      if (width && width >= 300 && width <= 800) {
        els.sidebar.style.width = width + 'px';
        document.documentElement.style.setProperty('--tsb-sidebar-width', width + 'px');
      }
      state.autoScroll = autoScroll;
      updateAutoScrollBtn();
    });
  }

  // ─── Wire Events ──────────────────────────────────────────────
  function wireEvents() {
    // Header buttons
    els.closeBtn.addEventListener('click', closeSidebar);

    els.autoscrollBtn.addEventListener('click', () => {
      state.autoScroll = !state.autoScroll;
      updateAutoScrollBtn();
      // Persist
      chrome.storage.local.get('tsb_settings', (r) => {
        const settings = r.tsb_settings || {};
        settings.autoScroll = state.autoScroll;
        chrome.storage.local.set({ tsb_settings: settings });
      });
    });

    els.settingsBtn.addEventListener('click', () => {
      chrome.runtime.sendMessage({ type: 'OPEN_DASHBOARD' });
    });

    // Language selector
    els.langSelect.addEventListener('change', (e) => {
      state.selectedTrackUrl = e.target.value;
      if (state.selectedTrackUrl) {
        fetchTranscript(state.selectedTrackUrl);
      }
    });

    // Search
    let searchDebounce = null;
    els.searchInput.addEventListener('input', (e) => {
      clearTimeout(searchDebounce);
      searchDebounce = setTimeout(() => {
        applySearch(e.target.value);
      }, 200);
    });

    els.searchInput.addEventListener('keydown', (e) => {
      if (e.key === 'Escape') {
        els.searchInput.value = '';
        applySearch('');
      }
    });

    // Action buttons
    els.copyBtn.addEventListener('click', copyTranscript);
    els.saveBtn.addEventListener('click', saveTranscript);

    els.exportBtn.addEventListener('click', (e) => {
      e.stopPropagation();
      toggleExportMenu();
    });

    els.exportMenu.addEventListener('click', (e) => {
      const item = e.target.closest('[data-format]');
      if (!item) return;
      exportTranscript(item.dataset.format);
      closeExportMenu();
    });

    els.libraryBtn.addEventListener('click', () => {
      chrome.runtime.sendMessage({ type: 'OPEN_DASHBOARD' });
    });

    // Close export menu on outside click
    document.addEventListener('click', (e) => {
      if (!els.exportBtn.contains(e.target) && !els.exportMenu.contains(e.target)) {
        closeExportMenu();
      }
    });

    // SPA navigation
    window.addEventListener('tsb-video-changed', handleVideoChanged);

    // Keyboard shortcut: Escape to close sidebar
    document.addEventListener('keydown', (e) => {
      if (e.key === 'Escape' && state.isOpen && document.activeElement !== els.searchInput) {
        closeSidebar();
      }
    });
  }

  // ─── Message Listener ─────────────────────────────────────────
  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type === 'TOGGLE_SIDEBAR') {
      toggleSidebar();
      sendResponse({ ok: true });
    }
    return true;
  });

  // ─── Init ─────────────────────────────────────────────────────
  function init() {
    buildSidebar();
    cacheElements();
    initResizeHandle();
    wireEvents();
    loadSavedWidth();
  }

  // Run on DOM ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', init);
  } else {
    init();
  }
})();
