(function () {
  'use strict';

  function getPlayerResponse() {
    const scripts = document.querySelectorAll('script');
    for (const script of scripts) {
      const text = script.textContent;
      const match = text.match(/var\s+ytInitialPlayerResponse\s*=\s*(\{.+?\});/s);
      if (match) {
        try {
          return JSON.parse(match[1]);
        } catch {
          continue;
        }
      }
    }
    return null;
  }

  function getCaptionTracks(playerResponse) {
    const tracks =
      playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
    if (!tracks) return [];
    return tracks.map(track => ({
      url: track.baseUrl,
      label: track.name?.simpleText || track.languageCode,
      languageCode: track.languageCode,
      isAutoGenerated: track.kind === 'asr',
    }));
  }

  function getVideoMetadata(playerResponse) {
    const d = playerResponse?.videoDetails;
    if (!d) return null;
    return {
      id: d.videoId,
      title: d.title,
      channel: d.author,
      channelId: d.channelId,
      description: d.shortDescription || '',
      viewCount: parseInt(d.viewCount, 10) || 0,
      publishDate: d.publishDate || '',
    };
  }

  chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
    if (message.type === 'GET_VIDEO_DATA') {
      const playerResponse = getPlayerResponse();
      if (!playerResponse) {
        sendResponse({ error: 'No player response found on page' });
        return;
      }
      sendResponse({
        metadata: getVideoMetadata(playerResponse),
        captionTracks: getCaptionTracks(playerResponse),
      });
    }
    return true;
  });

  let lastUrl = location.href;
  const observer = new MutationObserver(() => {
    if (location.href !== lastUrl) {
      lastUrl = location.href;
      window.dispatchEvent(new CustomEvent('tsb-video-changed'));
    }
  });
  observer.observe(document.body, { childList: true, subtree: true });
})();
