export function extractPlayerResponse(html) {
  const match = html.match(/var\s+ytInitialPlayerResponse\s*=\s*(\{.+?\});/s);
  if (!match) return null;
  try {
    return JSON.parse(match[1]);
  } catch {
    return null;
  }
}

export function parseCaptionTracks(playerResponse) {
  const tracks =
    playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks;
  if (!tracks) return [];
  return tracks.map(track => ({
    url: track.baseUrl,
    label: track.name?.simpleText || track.languageCode,
    languageCode: track.languageCode,
    isAutoGenerated: track.kind === 'asr',
  }));
}

export function parseVideoMetadata(playerResponse) {
  const d = playerResponse?.videoDetails;
  if (!d) return null;
  return {
    id: d.videoId,
    title: d.title,
    channel: d.author,
    channelId: d.channelId,
    description: d.shortDescription || '',
    viewCount: parseInt(d.viewCount, 10) || 0,
    publishDate: d.publishDate || '',
  };
}
