chrome.action.onClicked.addListener(async (tab) => {
  if (tab.url?.includes('youtube.com/watch')) {
    await chrome.tabs.sendMessage(tab.id, { type: 'TOGGLE_SIDEBAR' });
  } else {
    chrome.tabs.create({ url: chrome.runtime.getURL('src/dashboard/dashboard.html') });
  }
});

chrome.runtime.onMessage.addListener((message, sender, sendResponse) => {
  if (message.type === 'FETCH_TRANSCRIPT') {
    fetchTranscriptFromUrl(message.captionUrl)
      .then(segments => sendResponse({ segments }))
      .catch(err => sendResponse({ error: err.message }));
    return true;
  }

  if (message.type === 'FETCH_PAGE_HTML') {
    fetch(message.url)
      .then(res => res.text())
      .then(html => sendResponse({ html }))
      .catch(err => sendResponse({ error: err.message }));
    return true;
  }

  if (message.type === 'FETCH_VIDEO_DATA') {
    fetchVideoData(message.videoId)
      .then(data => sendResponse(data))
      .catch(err => sendResponse({ error: err.message }));
    return true;
  }

  if (message.type === 'OPEN_DASHBOARD') {
    chrome.tabs.create({ url: chrome.runtime.getURL('src/dashboard/dashboard.html') });
    sendResponse({ ok: true });
    return true;
  }
});

async function fetchTranscriptFromUrl(captionUrl) {
  const response = await fetch(captionUrl);
  if (!response.ok) throw new Error(`Caption fetch failed: ${response.status}`);
  const xml = await response.text();
  return parseTimedTextXml(xml);
}

async function fetchVideoData(videoId) {
  const url = `https://www.youtube.com/watch?v=${videoId}`;
  const response = await fetch(url);
  if (!response.ok) throw new Error(`Page fetch failed: ${response.status}`);
  const html = await response.text();

  const match = html.match(/var\s+ytInitialPlayerResponse\s*=\s*(\{.+?\});/s);
  if (!match) throw new Error('No player response found');

  const playerResponse = JSON.parse(match[1]);
  const details = playerResponse?.videoDetails;
  const tracks = playerResponse?.captions?.playerCaptionsTracklistRenderer?.captionTracks || [];

  return {
    metadata: {
      id: details?.videoId,
      title: details?.title,
      channel: details?.author,
      channelId: details?.channelId,
      description: details?.shortDescription || '',
      viewCount: parseInt(details?.viewCount, 10) || 0,
      publishDate: details?.publishDate || '',
    },
    captionTracks: tracks.map(t => ({
      url: t.baseUrl,
      label: t.name?.simpleText || t.languageCode,
      languageCode: t.languageCode,
      isAutoGenerated: t.kind === 'asr',
    })),
  };
}

function parseTimedTextXml(xml) {
  const ENTITIES = { '&amp;': '&', '&lt;': '<', '&gt;': '>', '&quot;': '"', '&apos;': "'", '&#39;': "'" };
  function decode(text) {
    return text.replace(/&(?:amp|lt|gt|quot|apos|#39);/g, m => ENTITIES[m] || m).replace(/<[^>]+>/g, '');
  }
  const segments = [];

  // Try srv3 format first: <p t="start_ms" d="duration_ms">text</p>
  const srv3Regex = /<p\s[^>]*?t="(\d+)"[^>]*?d="(\d+)"[^>]*>([\s\S]*?)<\/p>/g;
  let m;
  while ((m = srv3Regex.exec(xml)) !== null) {
    const text = decode(m[3].trim());
    if (text) {
      segments.push({ start: parseInt(m[1]) / 1000, duration: parseInt(m[2]) / 1000, text });
    }
  }

  // Fallback: legacy format <text start="secs" dur="secs">text</text>
  if (segments.length === 0) {
    const legacyRegex = /<text\s+start="([^"]+)"\s+dur="([^"]+)"[^>]*>([\s\S]*?)<\/text>/g;
    while ((m = legacyRegex.exec(xml)) !== null) {
      const text = decode(m[3].trim());
      if (text) {
        segments.push({ start: parseFloat(m[1]), duration: parseFloat(m[2]), text });
      }
    }
  }

  return segments;
}
