import { describe, it, expect } from 'vitest';
import { extractPlayerResponse, parseCaptionTracks, parseVideoMetadata } from '../../src/sources/youtube/innertube.js';

const MOCK_PLAYER_RESPONSE = {
  videoDetails: {
    videoId: 'dQw4w9WgXcQ',
    title: 'Test Video Title',
    author: 'Test Channel',
    channelId: 'UCtest123',
    shortDescription: 'A test video description',
    viewCount: '125000',
    publishDate: '2026-03-15',
  },
  captions: {
    playerCaptionsTracklistRenderer: {
      captionTracks: [
        {
          baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en',
          name: { simpleText: 'English' },
          languageCode: 'en',
          kind: 'asr',
        },
        {
          baseUrl: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=es',
          name: { simpleText: 'Spanish' },
          languageCode: 'es',
        },
      ],
    },
  },
};

const MOCK_HTML = `
  <html><body>
  <script>var ytInitialPlayerResponse = ${JSON.stringify(MOCK_PLAYER_RESPONSE)};</script>
  </body></html>
`;

const MOCK_HTML_NO_CAPTIONS = `
  <html><body>
  <script>var ytInitialPlayerResponse = ${JSON.stringify({
    videoDetails: MOCK_PLAYER_RESPONSE.videoDetails,
  })};</script>
  </body></html>
`;

describe('innertube — extractPlayerResponse', () => {
  it('extracts ytInitialPlayerResponse from HTML', () => {
    const result = extractPlayerResponse(MOCK_HTML);
    expect(result.videoDetails.videoId).toBe('dQw4w9WgXcQ');
  });

  it('returns null when ytInitialPlayerResponse is not found', () => {
    const result = extractPlayerResponse('<html><body></body></html>');
    expect(result).toBeNull();
  });
});

describe('innertube — parseCaptionTracks', () => {
  it('extracts caption tracks with language and URL', () => {
    const tracks = parseCaptionTracks(MOCK_PLAYER_RESPONSE);
    expect(tracks).toHaveLength(2);
    expect(tracks[0]).toEqual({
      url: 'https://www.youtube.com/api/timedtext?v=dQw4w9WgXcQ&lang=en',
      label: 'English',
      languageCode: 'en',
      isAutoGenerated: true,
    });
    expect(tracks[1].isAutoGenerated).toBe(false);
  });

  it('returns empty array when no captions exist', () => {
    const tracks = parseCaptionTracks({ videoDetails: {} });
    expect(tracks).toEqual([]);
  });
});

describe('innertube — parseVideoMetadata', () => {
  it('extracts video metadata', () => {
    const meta = parseVideoMetadata(MOCK_PLAYER_RESPONSE);
    expect(meta).toEqual({
      id: 'dQw4w9WgXcQ',
      title: 'Test Video Title',
      channel: 'Test Channel',
      channelId: 'UCtest123',
      description: 'A test video description',
      viewCount: 125000,
      publishDate: '2026-03-15',
    });
  });
});
